services:
  frontend:
    build:
      context: ./frontend-service
    ports:
      - "3000:3000"
    networks:
      - webnet
    develop:
      watch:
        - action: rebuild
          path: .

  inventory:
    build:
      context: ./inventory-service
    ports:
      - "3001:3001"
    networks:
      - webnet
    develop:
      watch:
        - action: rebuild
          path: .

  nginx:
    build:
      context: ./nginx
      args:
        NGINX_CONF: dev.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - inventory
    networks:
      - webnet
    develop:
      watch:
        - action: rebuild
          path: .

networks:
  webnet:
