services:
  frontend:
    build:
      context: ./frontend-service
    environment:
      - HOST=http://localhost
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - webnet
    develop:
      watch:
        - action: rebuild
          path: .
    depends_on:
      - emotion-detection

  inventory:
    build:
      context: ./inventory-service
    environment:
      - HOST=http://localhost
      - PORT=3001
      - DATABASE_HOST=inventory-db
      - DATABASE_PORT=5432
      - DATABASE_USER=inventory_user
      - DATABASE_PASSWORD=inventory_pass
      - DATABASE_NAME=inventory_db
    depends_on:
      inventory-db:
        condition: service_healthy
    ports:
      - "3001:3001"
    networks:
      - webnet
    develop:
      watch:
        - action: rebuild
          path: .

  inventory-db:
    build:
      context: ./inventory-service-db
    ports:
      - "5432:5432"
    volumes:
      - ./inventory-service-db/data:/var/lib/postgresql/data
    networks:
      - webnet
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U inventory_user -d inventory_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  digit-recognition:
    build:
      context: ./digit-recognition-service
    environment:
      - HOST=http://localhost
      - PORT=3002
    ports:
      - "3002:3002"
    networks:
      - webnet
    develop:
      watch:
        - action: rebuild
          path: .

  emotion-detection:
    build:
      context: ./emotion-detection-service
    environment:
      - HOST=http://localhost
      - PORT=3003
    ports:
      - "3003:3003"
    networks:
      - webnet
    develop:
      watch:
        - action: rebuild
          path: .

  nginx:
    build:
      context: ./nginx
      args:
        NGINX_CONF: dev.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - inventory
      - digit-recognition
      - emotion-detection
    networks:
      - webnet
    develop:
      watch:
        - action: rebuild
          path: .

networks:
  webnet:
